### ISSUE TITLE
Part GitHub

### ISSUE THREAD

**Issue by albaab** [Treballenequip/treball_en_equip#1]
- [x] Crear organització, integrants i projecte
- [x] Crear les issues
- [x] GitHub Pages i Bas
- [x] Wiki

**Comment by albaab** [comment]
Issues fetes i Wiki plantejada (anar omplint mentre es realitza la pràctica).

**Comment by FFernandezC** [comment]
Ja està penjat al BAS i guithub l'última versió del projecte.

**Comment by FFernandezC** [comment]
Wiki finalitzada, pot ser susceptible a canvis.
