### ISSUE TITLE
Part artística

### ISSUE THREAD

**Issue by albaab** [Treballenequip/treball_en_equip#2]
- [x] Logo amb SVG
- [x] Logo programat amb xml
- [x] Animació del Logo (Hover)
- [x] Estil coherent en tota la pràctica

**Comment by albaab** [comment]
### Possible codi pel Logo


<!DOCTYPE html>
<html>
<body>

    <svg height="230" width="500">
        <defs>
          <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" style="stop-color:rgb(0, 195, 255);stop-opacity:1" />
            <stop offset="100%" style="stop-color:rgb(153, 0, 255);stop-opacity:1" />
          </linearGradient>
        </defs>
        <ellipse cx="100" cy="70" rx="85" ry="45" fill="url(#grad1)" />
        <text fill="#ffffff" font-size="45" font-family="Monospace" x="50" y="86">Play</text>
        Sorry, your browser does not support inline SVG.
      </svg>

</body>
</html>

**Comment by FFernandezC** [comment]
He estat fent el Logo, se que falta alguna cosa dins de l'estrella. El logo es troba dins la carpeta "styles" en un HTML anomenat LOGO. De moment ho estic fent en aquest arxiu. Només em falta utilitzar una corba de Bezier, m'ho ha dit el profe per treure més nota en la part artística.

**Comment by FFernandezC** [comment]
El logo està completat amb <svg>. Es pot trobar la versió separada a .\styles\logo.html. En el menú principal del joc està implementat amb una petita animació en passar per sobre.

**Comment by FFernandezC** [comment]
Tota la part artística del projecte està finalitzada tant la part del menú, logo, etc. Com la part artística del joc amb els personatges fons i altres detalls.
