### ISSUE TITLE
Part programació

### ISSUE THREAD

**Issue by albaab** [Treballenequip/treball_en_equip#3]
- [x] Menú principal amb Vue.js
- [x] Estil coherent en tot el joc
- [x] Implementar el joc en Phaser.io
- [x] #5
- [x] Implementar menú de pausa (recomanable fer-ho amb Phaser.io)

**Comment by FFernandezC** [comment]
El menú està complet. El funcionament dels botons està fet amb VUE. A més, el CSS amb l'estil també està fet. El CSS del menú està a **.\styles\menu.css**. En el menú principal del joc està implementat amb una petita animació en passar per sobre.

**Comment by FFernandezC** [comment]
En el Menú d'opcions, s'ha de fer el "options.js" per guardar en un [JSON] les opcions escollides.

**Comment by Joelrumex** [comment]
El joc està complet. S'ha programat amb Phaser.io. També s'ha fet la implementació d'un menú de pausa
